# Generated by Django 3.1 on 2020-08-14 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Решение')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время отправки')),
                ('status', models.CharField(max_length=30, verbose_name='Статус решения')),
                ('task_id', models.PositiveIntegerField(default=0, verbose_name='ID решения')),
            ],
        ),
    ]
