# Generated by Django 3.1 on 2020-08-21 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20200817_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='redis_id',
        ),
    ]
